/* Generated by Yosys 0.9 (git sha1 UNKNOWN, gcc 7.5.0-3ubuntu1~18.04 -fPIC -Os) */

(* top =  1  *)
(* src = "mux2x1_struct.v:22" *)
module mux2x1_struct(clk, in0, in1, valid, reset, out, validout);
  (* src = "mux2x1_struct.v:50" *)
  wire [7:0] _00_;
  (* src = "mux2x1_struct.v:50" *)
  wire _01_;
  (* src = "mux2x1_struct.v:50" *)
  wire [7:0] _02_;
  (* src = "mux2x1_struct.v:50" *)
  wire _03_;
  (* src = "mux2x1_struct.v:50" *)
  wire [7:0] _04_;
  (* src = "mux2x1_struct.v:50" *)
  wire [7:0] _05_;
  (* src = "mux2x1_struct.v:25" *)
  input clk;
  (* src = "mux2x1_struct.v:26" *)
  input [7:0] in0;
  (* src = "mux2x1_struct.v:27" *)
  input [7:0] in1;
  (* src = "mux2x1_struct.v:32" *)
  output [7:0] out;
  (* src = "mux2x1_struct.v:29" *)
  input reset;
  (* src = "mux2x1_struct.v:38" *)
  wire selector_struct;
  (* src = "mux2x1_struct.v:28" *)
  input [1:0] valid;
  (* src = "mux2x1_struct.v:33" *)
  output validout;
  assign _05_[5] = valid[0] ? (* src = "mux2x1_struct.v:64" *) in0[5] : out[5];
  assign _05_[6] = valid[0] ? (* src = "mux2x1_struct.v:64" *) in0[6] : out[6];
  assign _05_[7] = valid[0] ? (* src = "mux2x1_struct.v:64" *) in0[7] : out[7];
  assign _04_[0] = valid[1] ? (* src = "mux2x1_struct.v:57" *) in1[0] : out[0];
  assign _04_[1] = valid[1] ? (* src = "mux2x1_struct.v:57" *) in1[1] : out[1];
  assign _04_[2] = valid[1] ? (* src = "mux2x1_struct.v:57" *) in1[2] : out[2];
  assign _04_[3] = valid[1] ? (* src = "mux2x1_struct.v:57" *) in1[3] : out[3];
  assign _04_[4] = valid[1] ? (* src = "mux2x1_struct.v:57" *) in1[4] : out[4];
  assign _04_[5] = valid[1] ? (* src = "mux2x1_struct.v:57" *) in1[5] : out[5];
  assign _04_[6] = valid[1] ? (* src = "mux2x1_struct.v:57" *) in1[6] : out[6];
  assign _04_[7] = valid[1] ? (* src = "mux2x1_struct.v:57" *) in1[7] : out[7];
  assign _03_ = selector_struct ? (* src = "mux2x1_struct.v:55" *) valid[1] : valid[0];
  assign _02_[0] = selector_struct ? (* src = "mux2x1_struct.v:55" *) _04_[0] : _05_[0];
  assign _02_[1] = selector_struct ? (* src = "mux2x1_struct.v:55" *) _04_[1] : _05_[1];
  assign _02_[2] = selector_struct ? (* src = "mux2x1_struct.v:55" *) _04_[2] : _05_[2];
  assign _02_[3] = selector_struct ? (* src = "mux2x1_struct.v:55" *) _04_[3] : _05_[3];
  assign _02_[4] = selector_struct ? (* src = "mux2x1_struct.v:55" *) _04_[4] : _05_[4];
  assign _02_[5] = selector_struct ? (* src = "mux2x1_struct.v:55" *) _04_[5] : _05_[5];
  assign _02_[6] = selector_struct ? (* src = "mux2x1_struct.v:55" *) _04_[6] : _05_[6];
  assign _02_[7] = selector_struct ? (* src = "mux2x1_struct.v:55" *) _04_[7] : _05_[7];
  assign _01_ = reset ? (* src = "mux2x1_struct.v:51" *) _03_ : 1'h0;
  assign _00_[0] = reset ? (* src = "mux2x1_struct.v:51" *) _02_[0] : 1'h0;
  assign _00_[1] = reset ? (* src = "mux2x1_struct.v:51" *) _02_[1] : 1'h0;
  assign _00_[2] = reset ? (* src = "mux2x1_struct.v:51" *) _02_[2] : 1'h0;
  assign _00_[3] = reset ? (* src = "mux2x1_struct.v:51" *) _02_[3] : 1'h0;
  assign _00_[4] = reset ? (* src = "mux2x1_struct.v:51" *) _02_[4] : 1'h0;
  assign _00_[5] = reset ? (* src = "mux2x1_struct.v:51" *) _02_[5] : 1'h0;
  assign _00_[6] = reset ? (* src = "mux2x1_struct.v:51" *) _02_[6] : 1'h0;
  assign _00_[7] = reset ? (* src = "mux2x1_struct.v:51" *) _02_[7] : 1'h0;
  assign _05_[0] = valid[0] ? (* src = "mux2x1_struct.v:64" *) in0[0] : out[0];
  assign _05_[1] = valid[0] ? (* src = "mux2x1_struct.v:64" *) in0[1] : out[1];
  assign _05_[2] = valid[0] ? (* src = "mux2x1_struct.v:64" *) in0[2] : out[2];
  assign _05_[3] = valid[0] ? (* src = "mux2x1_struct.v:64" *) in0[3] : out[3];
  assign _05_[4] = valid[0] ? (* src = "mux2x1_struct.v:64" *) in0[4] : out[4];
  (* src = "mux2x1_struct.v:50" *)
  DFF _40_ (
    .C(clk),
    .D(_01_),
    .Q(validout)
  );
  (* src = "mux2x1_struct.v:50" *)
  DFF _41_ (
    .C(clk),
    .D(_00_[0]),
    .Q(out[0])
  );
  (* src = "mux2x1_struct.v:50" *)
  DFF _42_ (
    .C(clk),
    .D(_00_[1]),
    .Q(out[1])
  );
  (* src = "mux2x1_struct.v:50" *)
  DFF _43_ (
    .C(clk),
    .D(_00_[2]),
    .Q(out[2])
  );
  (* src = "mux2x1_struct.v:50" *)
  DFF _44_ (
    .C(clk),
    .D(_00_[3]),
    .Q(out[3])
  );
  (* src = "mux2x1_struct.v:50" *)
  DFF _45_ (
    .C(clk),
    .D(_00_[4]),
    .Q(out[4])
  );
  (* src = "mux2x1_struct.v:50" *)
  DFF _46_ (
    .C(clk),
    .D(_00_[5]),
    .Q(out[5])
  );
  (* src = "mux2x1_struct.v:50" *)
  DFF _47_ (
    .C(clk),
    .D(_00_[6]),
    .Q(out[6])
  );
  (* src = "mux2x1_struct.v:50" *)
  DFF _48_ (
    .C(clk),
    .D(_00_[7]),
    .Q(out[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "mux2x1_struct.v:41" *)
  selector_struct sel (
    .clk(clk),
    .reset(reset),
    .sel(selector_struct)
  );
endmodule

(* src = "selector_struct.v:3" *)
module selector_struct(clk, reset, sel);
  (* src = "selector_struct.v:12" *)
  wire _0_;
  (* src = "selector_struct.v:17" *)
  wire _1_;
  (* src = "selector_struct.v:4" *)
  input clk;
  (* src = "selector_struct.v:5" *)
  input reset;
  (* src = "selector_struct.v:6" *)
  output sel;
  assign _0_ = reset ? (* src = "selector_struct.v:14" *) _1_ : 1'h0;
  assign _1_ = ~(* src = "selector_struct.v:17" *) sel;
  (* src = "selector_struct.v:12" *)
  DFF _4_ (
    .C(clk),
    .D(_0_),
    .Q(sel)
  );
endmodule
