/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "demuxfsynth.v:2" *)
module demuxfsynth(clk, reset, in0, in0_valid, out0, out1, valid_out0, valid_out1);
  (* src = "demuxfsynth.v:26" *)
  wire [7:0] _000_;
  (* src = "demuxfsynth.v:26" *)
  wire [7:0] _001_;
  (* src = "demuxfsynth.v:17" *)
  wire _002_;
  (* src = "demuxfsynth.v:26" *)
  wire _003_;
  (* src = "demuxfsynth.v:26" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  (* src = "demuxfsynth.v:4" *)
  input clk;
  (* src = "demuxfsynth.v:6" *)
  input [7:0] in0;
  (* src = "demuxfsynth.v:7" *)
  input in0_valid;
  (* src = "demuxfsynth.v:8" *)
  output [7:0] out0;
  (* src = "demuxfsynth.v:9" *)
  output [7:0] out1;
  (* src = "demuxfsynth.v:5" *)
  input reset;
  (* src = "demuxfsynth.v:14" *)
  wire selector;
  (* src = "demuxfsynth.v:10" *)
  output valid_out0;
  (* src = "demuxfsynth.v:11" *)
  output valid_out1;
  NOT _061_ (
    .A(reset),
    .Y(_021_)
  );
  NOR _062_ (
    .A(selector),
    .B(_021_),
    .Y(_002_)
  );
  NAND _063_ (
    .A(_002_),
    .B(in0_valid),
    .Y(_022_)
  );
  NOT _064_ (
    .A(selector),
    .Y(_023_)
  );
  NOR _065_ (
    .A(_023_),
    .B(_021_),
    .Y(_024_)
  );
  NAND _066_ (
    .A(_024_),
    .B(valid_out0),
    .Y(_025_)
  );
  NAND _067_ (
    .A(_025_),
    .B(_022_),
    .Y(_003_)
  );
  NAND _068_ (
    .A(_002_),
    .B(out1[0]),
    .Y(_026_)
  );
  NOT _069_ (
    .A(in0[0]),
    .Y(_027_)
  );
  NOT _070_ (
    .A(in0_valid),
    .Y(_028_)
  );
  NOR _071_ (
    .A(_028_),
    .B(_027_),
    .Y(_029_)
  );
  NAND _072_ (
    .A(_029_),
    .B(_024_),
    .Y(_030_)
  );
  NAND _073_ (
    .A(_030_),
    .B(_026_),
    .Y(_001_[0])
  );
  NAND _074_ (
    .A(_002_),
    .B(out1[1]),
    .Y(_031_)
  );
  NOT _075_ (
    .A(in0[1]),
    .Y(_032_)
  );
  NOR _076_ (
    .A(_032_),
    .B(_028_),
    .Y(_033_)
  );
  NAND _077_ (
    .A(_033_),
    .B(_024_),
    .Y(_034_)
  );
  NAND _078_ (
    .A(_034_),
    .B(_031_),
    .Y(_001_[1])
  );
  NAND _079_ (
    .A(_002_),
    .B(out1[2]),
    .Y(_035_)
  );
  NOT _080_ (
    .A(in0[2]),
    .Y(_036_)
  );
  NOR _081_ (
    .A(_036_),
    .B(_028_),
    .Y(_037_)
  );
  NAND _082_ (
    .A(_037_),
    .B(_024_),
    .Y(_038_)
  );
  NAND _083_ (
    .A(_038_),
    .B(_035_),
    .Y(_001_[2])
  );
  NAND _084_ (
    .A(_002_),
    .B(out1[3]),
    .Y(_039_)
  );
  NOT _085_ (
    .A(in0[3]),
    .Y(_040_)
  );
  NOR _086_ (
    .A(_040_),
    .B(_028_),
    .Y(_041_)
  );
  NAND _087_ (
    .A(_041_),
    .B(_024_),
    .Y(_042_)
  );
  NAND _088_ (
    .A(_042_),
    .B(_039_),
    .Y(_001_[3])
  );
  NAND _089_ (
    .A(_002_),
    .B(out1[4]),
    .Y(_043_)
  );
  NOT _090_ (
    .A(in0[4]),
    .Y(_044_)
  );
  NOR _091_ (
    .A(_044_),
    .B(_028_),
    .Y(_045_)
  );
  NAND _092_ (
    .A(_045_),
    .B(_024_),
    .Y(_046_)
  );
  NAND _093_ (
    .A(_046_),
    .B(_043_),
    .Y(_001_[4])
  );
  NAND _094_ (
    .A(_002_),
    .B(out1[5]),
    .Y(_047_)
  );
  NOT _095_ (
    .A(in0[5]),
    .Y(_048_)
  );
  NOR _096_ (
    .A(_048_),
    .B(_028_),
    .Y(_049_)
  );
  NAND _097_ (
    .A(_049_),
    .B(_024_),
    .Y(_050_)
  );
  NAND _098_ (
    .A(_050_),
    .B(_047_),
    .Y(_001_[5])
  );
  NAND _099_ (
    .A(_002_),
    .B(out1[6]),
    .Y(_051_)
  );
  NOT _100_ (
    .A(in0[6]),
    .Y(_052_)
  );
  NOR _101_ (
    .A(_052_),
    .B(_028_),
    .Y(_053_)
  );
  NAND _102_ (
    .A(_053_),
    .B(_024_),
    .Y(_054_)
  );
  NAND _103_ (
    .A(_054_),
    .B(_051_),
    .Y(_001_[6])
  );
  NAND _104_ (
    .A(_002_),
    .B(out1[7]),
    .Y(_055_)
  );
  NOT _105_ (
    .A(in0[7]),
    .Y(_056_)
  );
  NOR _106_ (
    .A(_056_),
    .B(_028_),
    .Y(_057_)
  );
  NAND _107_ (
    .A(_057_),
    .B(_024_),
    .Y(_058_)
  );
  NAND _108_ (
    .A(_058_),
    .B(_055_),
    .Y(_001_[7])
  );
  NAND _109_ (
    .A(_029_),
    .B(_002_),
    .Y(_059_)
  );
  NAND _110_ (
    .A(_024_),
    .B(out0[0]),
    .Y(_060_)
  );
  NAND _111_ (
    .A(_060_),
    .B(_059_),
    .Y(_000_[0])
  );
  NAND _112_ (
    .A(_033_),
    .B(_002_),
    .Y(_005_)
  );
  NAND _113_ (
    .A(_024_),
    .B(out0[1]),
    .Y(_006_)
  );
  NAND _114_ (
    .A(_006_),
    .B(_005_),
    .Y(_000_[1])
  );
  NAND _115_ (
    .A(_037_),
    .B(_002_),
    .Y(_007_)
  );
  NAND _116_ (
    .A(_024_),
    .B(out0[2]),
    .Y(_008_)
  );
  NAND _117_ (
    .A(_008_),
    .B(_007_),
    .Y(_000_[2])
  );
  NAND _118_ (
    .A(_041_),
    .B(_002_),
    .Y(_009_)
  );
  NAND _119_ (
    .A(_024_),
    .B(out0[3]),
    .Y(_010_)
  );
  NAND _120_ (
    .A(_010_),
    .B(_009_),
    .Y(_000_[3])
  );
  NAND _121_ (
    .A(_045_),
    .B(_002_),
    .Y(_011_)
  );
  NAND _122_ (
    .A(_024_),
    .B(out0[4]),
    .Y(_012_)
  );
  NAND _123_ (
    .A(_012_),
    .B(_011_),
    .Y(_000_[4])
  );
  NAND _124_ (
    .A(_049_),
    .B(_002_),
    .Y(_013_)
  );
  NAND _125_ (
    .A(_024_),
    .B(out0[5]),
    .Y(_014_)
  );
  NAND _126_ (
    .A(_014_),
    .B(_013_),
    .Y(_000_[5])
  );
  NAND _127_ (
    .A(_053_),
    .B(_002_),
    .Y(_015_)
  );
  NAND _128_ (
    .A(_024_),
    .B(out0[6]),
    .Y(_016_)
  );
  NAND _129_ (
    .A(_016_),
    .B(_015_),
    .Y(_000_[6])
  );
  NAND _130_ (
    .A(_057_),
    .B(_002_),
    .Y(_017_)
  );
  NAND _131_ (
    .A(_024_),
    .B(out0[7]),
    .Y(_018_)
  );
  NAND _132_ (
    .A(_018_),
    .B(_017_),
    .Y(_000_[7])
  );
  NAND _133_ (
    .A(_002_),
    .B(valid_out1),
    .Y(_019_)
  );
  NAND _134_ (
    .A(_024_),
    .B(in0_valid),
    .Y(_020_)
  );
  NAND _135_ (
    .A(_020_),
    .B(_019_),
    .Y(_004_)
  );
  DFF _136_ (
    .C(clk),
    .D(_000_[0]),
    .Q(out0[0])
  );
  DFF _137_ (
    .C(clk),
    .D(_000_[1]),
    .Q(out0[1])
  );
  DFF _138_ (
    .C(clk),
    .D(_000_[2]),
    .Q(out0[2])
  );
  DFF _139_ (
    .C(clk),
    .D(_000_[3]),
    .Q(out0[3])
  );
  DFF _140_ (
    .C(clk),
    .D(_000_[4]),
    .Q(out0[4])
  );
  DFF _141_ (
    .C(clk),
    .D(_000_[5]),
    .Q(out0[5])
  );
  DFF _142_ (
    .C(clk),
    .D(_000_[6]),
    .Q(out0[6])
  );
  DFF _143_ (
    .C(clk),
    .D(_000_[7]),
    .Q(out0[7])
  );
  DFF _144_ (
    .C(clk),
    .D(_001_[0]),
    .Q(out1[0])
  );
  DFF _145_ (
    .C(clk),
    .D(_001_[1]),
    .Q(out1[1])
  );
  DFF _146_ (
    .C(clk),
    .D(_001_[2]),
    .Q(out1[2])
  );
  DFF _147_ (
    .C(clk),
    .D(_001_[3]),
    .Q(out1[3])
  );
  DFF _148_ (
    .C(clk),
    .D(_001_[4]),
    .Q(out1[4])
  );
  DFF _149_ (
    .C(clk),
    .D(_001_[5]),
    .Q(out1[5])
  );
  DFF _150_ (
    .C(clk),
    .D(_001_[6]),
    .Q(out1[6])
  );
  DFF _151_ (
    .C(clk),
    .D(_001_[7]),
    .Q(out1[7])
  );
  DFF _152_ (
    .C(clk),
    .D(_003_),
    .Q(valid_out0)
  );
  DFF _153_ (
    .C(clk),
    .D(_004_),
    .Q(valid_out1)
  );
  DFF _154_ (
    .C(clk),
    .D(_002_),
    .Q(selector)
  );
endmodule
