/* Generated by Yosys 0.9 (git sha1 UNKNOWN, gcc 7.5.0-3ubuntu1~18.04 -fPIC -Os) */

(* top =  1  *)
(* src = "demux1x2_struct.v:23" *)
module demux1x2_struct(in, clk, reset, valid, out0, out1, validout);
  (* src = "demux1x2_struct.v:50" *)
  wire [7:0] _00_;
  (* src = "demux1x2_struct.v:50" *)
  wire [7:0] _01_;
  (* src = "demux1x2_struct.v:42" *)
  wire _02_;
  (* src = "demux1x2_struct.v:50" *)
  wire [1:0] _03_;
  (* src = "demux1x2_struct.v:46" *)
  wire _04_;
  wire _05_;
  wire _06_;
  wire [7:0] _07_;
  wire [7:0] _08_;
  wire [7:0] _09_;
  wire [7:0] _10_;
  (* src = "demux1x2_struct.v:26" *)
  input clk;
  (* src = "demux1x2_struct.v:25" *)
  input [7:0] in;
  (* src = "demux1x2_struct.v:38" *)
  wire [7:0] node0;
  (* src = "demux1x2_struct.v:39" *)
  wire [7:0] node1;
  (* src = "demux1x2_struct.v:31" *)
  output [7:0] out0;
  (* src = "demux1x2_struct.v:32" *)
  output [7:0] out1;
  (* src = "demux1x2_struct.v:27" *)
  input reset;
  (* src = "demux1x2_struct.v:37" *)
  wire selector;
  (* src = "demux1x2_struct.v:28" *)
  input valid;
  (* src = "demux1x2_struct.v:33" *)
  output [1:0] validout;
  assign _07_[1] = valid ? (* src = "demux1x2_struct.v:56" *) in[1] : node0[1];
  assign _07_[2] = valid ? (* src = "demux1x2_struct.v:56" *) in[2] : node0[2];
  assign _07_[3] = valid ? (* src = "demux1x2_struct.v:56" *) in[3] : node0[3];
  assign _07_[4] = valid ? (* src = "demux1x2_struct.v:56" *) in[4] : node0[4];
  assign _07_[5] = valid ? (* src = "demux1x2_struct.v:56" *) in[5] : node0[5];
  assign _07_[6] = valid ? (* src = "demux1x2_struct.v:56" *) in[6] : node0[6];
  assign _07_[7] = valid ? (* src = "demux1x2_struct.v:56" *) in[7] : node0[7];
  assign _06_ = selector ? (* src = "demux1x2_struct.v:55" *) valid : validout[0];
  assign _03_[0] = reset ? (* src = "demux1x2_struct.v:51" *) _06_ : validout[0];
  assign _08_[0] = selector ? (* src = "demux1x2_struct.v:55" *) _07_[0] : node0[0];
  assign _08_[1] = selector ? (* src = "demux1x2_struct.v:55" *) _07_[1] : node0[1];
  assign _08_[2] = selector ? (* src = "demux1x2_struct.v:55" *) _07_[2] : node0[2];
  assign _08_[3] = selector ? (* src = "demux1x2_struct.v:55" *) _07_[3] : node0[3];
  assign _08_[4] = selector ? (* src = "demux1x2_struct.v:55" *) _07_[4] : node0[4];
  assign _08_[5] = selector ? (* src = "demux1x2_struct.v:55" *) _07_[5] : node0[5];
  assign _08_[6] = selector ? (* src = "demux1x2_struct.v:55" *) _07_[6] : node0[6];
  assign _08_[7] = selector ? (* src = "demux1x2_struct.v:55" *) _07_[7] : node0[7];
  assign _00_[0] = reset ? (* src = "demux1x2_struct.v:51" *) _08_[0] : 1'h0;
  assign _00_[1] = reset ? (* src = "demux1x2_struct.v:51" *) _08_[1] : 1'h0;
  assign _00_[2] = reset ? (* src = "demux1x2_struct.v:51" *) _08_[2] : 1'h0;
  assign _00_[3] = reset ? (* src = "demux1x2_struct.v:51" *) _08_[3] : 1'h0;
  assign _00_[4] = reset ? (* src = "demux1x2_struct.v:51" *) _08_[4] : 1'h0;
  assign _00_[5] = reset ? (* src = "demux1x2_struct.v:51" *) _08_[5] : 1'h0;
  assign _00_[6] = reset ? (* src = "demux1x2_struct.v:51" *) _08_[6] : 1'h0;
  assign _00_[7] = reset ? (* src = "demux1x2_struct.v:51" *) _08_[7] : 1'h0;
  assign _01_[0] = reset ? (* src = "demux1x2_struct.v:51" *) _10_[0] : 1'h0;
  assign _01_[1] = reset ? (* src = "demux1x2_struct.v:51" *) _10_[1] : 1'h0;
  assign _01_[2] = reset ? (* src = "demux1x2_struct.v:51" *) _10_[2] : 1'h0;
  assign _01_[3] = reset ? (* src = "demux1x2_struct.v:51" *) _10_[3] : 1'h0;
  assign _01_[4] = reset ? (* src = "demux1x2_struct.v:51" *) _10_[4] : 1'h0;
  assign _01_[5] = reset ? (* src = "demux1x2_struct.v:51" *) _10_[5] : 1'h0;
  assign _01_[6] = reset ? (* src = "demux1x2_struct.v:51" *) _10_[6] : 1'h0;
  assign _01_[7] = reset ? (* src = "demux1x2_struct.v:51" *) _10_[7] : 1'h0;
  assign _09_[0] = valid ? (* src = "demux1x2_struct.v:64" *) in[0] : node1[0];
  assign _09_[1] = valid ? (* src = "demux1x2_struct.v:64" *) in[1] : node1[1];
  assign _09_[2] = valid ? (* src = "demux1x2_struct.v:64" *) in[2] : node1[2];
  assign _09_[3] = valid ? (* src = "demux1x2_struct.v:64" *) in[3] : node1[3];
  assign _09_[4] = valid ? (* src = "demux1x2_struct.v:64" *) in[4] : node1[4];
  assign _09_[5] = valid ? (* src = "demux1x2_struct.v:64" *) in[5] : node1[5];
  assign _09_[6] = valid ? (* src = "demux1x2_struct.v:64" *) in[6] : node1[6];
  assign _09_[7] = valid ? (* src = "demux1x2_struct.v:64" *) in[7] : node1[7];
  assign _10_[0] = selector ? (* src = "demux1x2_struct.v:55" *) node1[0] : _09_[0];
  assign _10_[1] = selector ? (* src = "demux1x2_struct.v:55" *) node1[1] : _09_[1];
  assign _10_[2] = selector ? (* src = "demux1x2_struct.v:55" *) node1[2] : _09_[2];
  assign _10_[3] = selector ? (* src = "demux1x2_struct.v:55" *) node1[3] : _09_[3];
  assign _10_[4] = selector ? (* src = "demux1x2_struct.v:55" *) node1[4] : _09_[4];
  assign _10_[5] = selector ? (* src = "demux1x2_struct.v:55" *) node1[5] : _09_[5];
  assign _10_[6] = selector ? (* src = "demux1x2_struct.v:55" *) node1[6] : _09_[6];
  assign _10_[7] = selector ? (* src = "demux1x2_struct.v:55" *) node1[7] : _09_[7];
  assign _02_ = reset ? (* src = "demux1x2_struct.v:43" *) _04_ : 1'h0;
  assign _05_ = selector ? (* src = "demux1x2_struct.v:55" *) validout[1] : valid;
  assign _03_[1] = reset ? (* src = "demux1x2_struct.v:51" *) _05_ : validout[1];
  assign _07_[0] = valid ? (* src = "demux1x2_struct.v:56" *) in[0] : node0[0];
  assign _04_ = ~(* src = "demux1x2_struct.v:46" *) selector;
  (* src = "demux1x2_struct.v:76" *)
  DFF _65_ (
    .C(clk),
    .D(node0[0]),
    .Q(out0[0])
  );
  (* src = "demux1x2_struct.v:76" *)
  DFF _66_ (
    .C(clk),
    .D(node0[1]),
    .Q(out0[1])
  );
  (* src = "demux1x2_struct.v:76" *)
  DFF _67_ (
    .C(clk),
    .D(node0[2]),
    .Q(out0[2])
  );
  (* src = "demux1x2_struct.v:76" *)
  DFF _68_ (
    .C(clk),
    .D(node0[3]),
    .Q(out0[3])
  );
  (* src = "demux1x2_struct.v:76" *)
  DFF _69_ (
    .C(clk),
    .D(node0[4]),
    .Q(out0[4])
  );
  (* src = "demux1x2_struct.v:76" *)
  DFF _70_ (
    .C(clk),
    .D(node0[5]),
    .Q(out0[5])
  );
  (* src = "demux1x2_struct.v:76" *)
  DFF _71_ (
    .C(clk),
    .D(node0[6]),
    .Q(out0[6])
  );
  (* src = "demux1x2_struct.v:76" *)
  DFF _72_ (
    .C(clk),
    .D(node0[7]),
    .Q(out0[7])
  );
  (* src = "demux1x2_struct.v:76" *)
  DFF _73_ (
    .C(clk),
    .D(node1[0]),
    .Q(out1[0])
  );
  (* src = "demux1x2_struct.v:76" *)
  DFF _74_ (
    .C(clk),
    .D(node1[1]),
    .Q(out1[1])
  );
  (* src = "demux1x2_struct.v:76" *)
  DFF _75_ (
    .C(clk),
    .D(node1[2]),
    .Q(out1[2])
  );
  (* src = "demux1x2_struct.v:76" *)
  DFF _76_ (
    .C(clk),
    .D(node1[3]),
    .Q(out1[3])
  );
  (* src = "demux1x2_struct.v:76" *)
  DFF _77_ (
    .C(clk),
    .D(node1[4]),
    .Q(out1[4])
  );
  (* src = "demux1x2_struct.v:76" *)
  DFF _78_ (
    .C(clk),
    .D(node1[5]),
    .Q(out1[5])
  );
  (* src = "demux1x2_struct.v:76" *)
  DFF _79_ (
    .C(clk),
    .D(node1[6]),
    .Q(out1[6])
  );
  (* src = "demux1x2_struct.v:76" *)
  DFF _80_ (
    .C(clk),
    .D(node1[7]),
    .Q(out1[7])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _81_ (
    .C(clk),
    .D(_03_[0]),
    .Q(validout[0])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _82_ (
    .C(clk),
    .D(_03_[1]),
    .Q(validout[1])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _83_ (
    .C(clk),
    .D(_00_[0]),
    .Q(node0[0])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _84_ (
    .C(clk),
    .D(_00_[1]),
    .Q(node0[1])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _85_ (
    .C(clk),
    .D(_00_[2]),
    .Q(node0[2])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _86_ (
    .C(clk),
    .D(_00_[3]),
    .Q(node0[3])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _87_ (
    .C(clk),
    .D(_00_[4]),
    .Q(node0[4])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _88_ (
    .C(clk),
    .D(_00_[5]),
    .Q(node0[5])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _89_ (
    .C(clk),
    .D(_00_[6]),
    .Q(node0[6])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _90_ (
    .C(clk),
    .D(_00_[7]),
    .Q(node0[7])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _91_ (
    .C(clk),
    .D(_01_[0]),
    .Q(node1[0])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _92_ (
    .C(clk),
    .D(_01_[1]),
    .Q(node1[1])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _93_ (
    .C(clk),
    .D(_01_[2]),
    .Q(node1[2])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _94_ (
    .C(clk),
    .D(_01_[3]),
    .Q(node1[3])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _95_ (
    .C(clk),
    .D(_01_[4]),
    .Q(node1[4])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _96_ (
    .C(clk),
    .D(_01_[5]),
    .Q(node1[5])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _97_ (
    .C(clk),
    .D(_01_[6]),
    .Q(node1[6])
  );
  (* src = "demux1x2_struct.v:50" *)
  DFF _98_ (
    .C(clk),
    .D(_01_[7]),
    .Q(node1[7])
  );
  (* src = "demux1x2_struct.v:42" *)
  DFF _99_ (
    .C(clk),
    .D(_02_),
    .Q(selector)
  );
endmodule
