/* Generated by Yosys 0.9 (git sha1 UNKNOWN, gcc 7.5.0-3ubuntu1~18.04 -fPIC -Os) */

(* top =  1  *)
(* src = "paralelltoserial_IDLE.v:7" *)
module paralelo_a_serial_IDLE(active, reset, clk32f, out);
  (* src = "paralelltoserial_IDLE.v:28" *)
  wire _00_;
  (* src = "paralelltoserial_IDLE.v:28" *)
  wire [2:0] _01_;
  (* src = "paralelltoserial_IDLE.v:36" *)
  (* unused_bits = "3" *)
  wire [31:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [2:0] _07_;
  wire [1:0] _08_;
  wire [2:0] _09_;
  wire [1:0] _10_;
  wire _11_;
  wire [2:0] _12_;
  wire [2:0] _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:432" *)
  wire [6:0] _20_;
  (* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:428" *)
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  (* src = "paralelltoserial_IDLE.v:36|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2" *)
  wire [31:0] _26_;
  (* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:445" *)
  wire _27_;
  (* src = "paralelltoserial_IDLE.v:9" *)
  input active;
  (* src = "paralelltoserial_IDLE.v:11" *)
  input clk32f;
  (* src = "paralelltoserial_IDLE.v:17" *)
  wire idle0;
  (* src = "paralelltoserial_IDLE.v:17" *)
  wire idle1;
  (* src = "paralelltoserial_IDLE.v:17" *)
  wire idle2;
  (* src = "paralelltoserial_IDLE.v:17" *)
  wire idle3;
  (* src = "paralelltoserial_IDLE.v:17" *)
  wire idle4;
  (* src = "paralelltoserial_IDLE.v:17" *)
  wire idle5;
  (* src = "paralelltoserial_IDLE.v:17" *)
  wire idle6;
  (* src = "paralelltoserial_IDLE.v:17" *)
  wire idle7;
  (* src = "paralelltoserial_IDLE.v:12" *)
  output out;
  (* src = "paralelltoserial_IDLE.v:10" *)
  input reset;
  (* src = "paralelltoserial_IDLE.v:18" *)
  wire [2:0] selector;
  assign _14_ = _03_ |(* src = "paralelltoserial_IDLE.v:43|paralelltoserial_IDLE.v:37" *)  _12_[2];
  assign _15_ = _04_ |(* src = "paralelltoserial_IDLE.v:42|paralelltoserial_IDLE.v:37" *)  _12_[2];
  assign _05_ = _02_[0] |(* src = "paralelltoserial_IDLE.v:41|paralelltoserial_IDLE.v:37" *)  _13_[1];
  assign _16_ = _05_ |(* src = "paralelltoserial_IDLE.v:41|paralelltoserial_IDLE.v:37" *)  selector[2];
  assign _17_ = _06_ |(* src = "paralelltoserial_IDLE.v:40|paralelltoserial_IDLE.v:37" *)  selector[2];
  assign _03_ = _02_[0] |(* src = "paralelltoserial_IDLE.v:39|paralelltoserial_IDLE.v:37" *)  selector[1];
  assign _18_ = _03_ |(* src = "paralelltoserial_IDLE.v:39|paralelltoserial_IDLE.v:37" *)  selector[2];
  assign _07_[2] = _20_[4] |(* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:441" *)  _20_[5];
  assign _08_[0] = _07_[0] |(* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:441" *)  _07_[1];
  assign _08_[1] = _07_[2] |(* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:441" *)  _20_[6];
  assign _21_ = _08_[0] |(* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:441" *)  _08_[1];
  assign _09_[0] = _23_ |(* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:445" *)  _07_[0];
  assign _07_[1] = _20_[2] |(* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:445" *)  _20_[3];
  assign _09_[2] = _20_[4] |(* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:445" *)  _24_;
  assign _10_[0] = _09_[0] |(* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:445" *)  _07_[1];
  assign _10_[1] = _09_[2] |(* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:445" *)  _25_;
  assign _27_ = _10_[0] |(* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:445" *)  _10_[1];
  assign _06_ = selector[0] |(* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37" *)  _13_[1];
  assign _19_ = _06_ |(* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37" *)  _12_[2];
  assign _04_ = selector[0] |(* src = "paralelltoserial_IDLE.v:38|paralelltoserial_IDLE.v:37" *)  selector[1];
  assign _11_ = _04_ |(* src = "paralelltoserial_IDLE.v:38|paralelltoserial_IDLE.v:37" *)  selector[2];
  assign _07_[0] = ~(* src = "paralelltoserial_IDLE.v:43|paralelltoserial_IDLE.v:37" *) _14_;
  assign _20_[2] = ~(* src = "paralelltoserial_IDLE.v:42|paralelltoserial_IDLE.v:37" *) _15_;
  assign _20_[3] = ~(* src = "paralelltoserial_IDLE.v:41|paralelltoserial_IDLE.v:37" *) _16_;
  assign _20_[4] = ~(* src = "paralelltoserial_IDLE.v:40|paralelltoserial_IDLE.v:37" *) _17_;
  assign _24_ = ~(* src = "paralelltoserial_IDLE.v:39|paralelltoserial_IDLE.v:37" *) _18_;
  assign _25_ = ~(* src = "paralelltoserial_IDLE.v:38|paralelltoserial_IDLE.v:37" *) _11_;
  assign _23_ = ~(* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37" *) _19_;
  assign _00_ = reset ? (* src = "paralelltoserial_IDLE.v:29" *) _22_ : 1'h0;
  assign idle0 = ~(* src = "paralelltoserial_IDLE.v:22" *) active;
  assign _22_ = _27_ ? (* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:445" *) _21_ : 1'h0;
  assign _01_[0] = reset ? (* src = "paralelltoserial_IDLE.v:29" *) _02_[0] : 1'h1;
  assign _01_[1] = reset ? (* src = "paralelltoserial_IDLE.v:29" *) _02_[1] : 1'h1;
  assign _01_[2] = reset ? (* src = "paralelltoserial_IDLE.v:29" *) _02_[2] : 1'h1;
  (* src = "paralelltoserial_IDLE.v:28" *)
  DFF _62_ (
    .C(clk32f),
    .D(_00_),
    .Q(out)
  );
  (* src = "paralelltoserial_IDLE.v:28" *)
  DFF _63_ (
    .C(clk32f),
    .D(_01_[0]),
    .Q(selector[0])
  );
  (* src = "paralelltoserial_IDLE.v:28" *)
  DFF _64_ (
    .C(clk32f),
    .D(_01_[1]),
    .Q(selector[1])
  );
  (* src = "paralelltoserial_IDLE.v:28" *)
  DFF _65_ (
    .C(clk32f),
    .D(_01_[2]),
    .Q(selector[2])
  );
  assign _12_[2] = selector[2] ^(* src = "paralelltoserial_IDLE.v:42|paralelltoserial_IDLE.v:37" *)  1'h1;
  assign _13_[1] = selector[1] ^(* src = "paralelltoserial_IDLE.v:40|paralelltoserial_IDLE.v:37" *)  1'h1;
  assign _02_[0] = selector[0] ^(* src = "paralelltoserial_IDLE.v:39|paralelltoserial_IDLE.v:37" *)  1'h1;
  assign _20_[6] = idle0 &(* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:434" *)  _25_;
  assign _20_[5] = active &(* src = "paralelltoserial_IDLE.v:44|paralelltoserial_IDLE.v:37|<techmap.v>:434" *)  _24_;
  assign _02_[1] = selector[1] ^(* src = "paralelltoserial_IDLE.v:36|<techmap.v>:263" *)  selector[0];
  assign _02_[2] = selector[2] ^(* src = "paralelltoserial_IDLE.v:36|<techmap.v>:263" *)  _26_[1];
  assign _26_[1] = selector[1] &(* src = "paralelltoserial_IDLE.v:36|<techmap.v>:260|<techmap.v>:221" *)  selector[0];
  assign _02_[31:4] = 28'h0000000;
  assign _09_[1] = _07_[1];
  assign _12_[1:0] = selector[1:0];
  assign { _13_[2], _13_[0] } = { selector[2], _02_[0] };
  assign _20_[1:0] = { _07_[0], 1'h0 };
  assign { _26_[31:2], _26_[0] } = { 29'h00000000, _02_[3], selector[0] };
  assign idle1 = active;
  assign idle2 = 1'h1;
  assign idle3 = 1'h1;
  assign idle4 = 1'h1;
  assign idle5 = 1'h1;
  assign idle6 = 1'h0;
  assign idle7 = 1'h0;
endmodule
