/* Generated by Yosys 0.9 (git sha1 UNKNOWN, gcc 7.5.0-3ubuntu1~18.04 -fPIC -Os) */

(* top =  1  *)
(* src = "./src/mux2x1_struct.v:21" *)
module mux2x1_struct(clk, in0, in1, valid, reset, out, validout);
  (* src = "./src/mux2x1_struct.v:46" *)
  wire [7:0] _00_;
  (* src = "./src/mux2x1_struct.v:36" *)
  wire _01_;
  (* src = "./src/mux2x1_struct.v:46" *)
  wire _02_;
  (* src = "./src/mux2x1_struct.v:40" *)
  wire _03_;
  wire [7:0] _04_;
  wire [7:0] _05_;
  wire _06_;
  wire [7:0] _07_;
  (* src = "./src/mux2x1_struct.v:24" *)
  input clk;
  (* src = "./src/mux2x1_struct.v:25" *)
  input [7:0] in0;
  (* src = "./src/mux2x1_struct.v:26" *)
  input [7:0] in1;
  (* src = "./src/mux2x1_struct.v:31" *)
  output [7:0] out;
  (* src = "./src/mux2x1_struct.v:28" *)
  input reset;
  (* src = "./src/mux2x1_struct.v:34" *)
  wire selector;
  (* src = "./src/mux2x1_struct.v:27" *)
  input [1:0] valid;
  (* src = "./src/mux2x1_struct.v:32" *)
  output validout;
  assign _00_[1] = reset ? (* src = "./src/mux2x1_struct.v:47" *) _05_[1] : 1'h0;
  assign _00_[2] = reset ? (* src = "./src/mux2x1_struct.v:47" *) _05_[2] : 1'h0;
  assign _00_[3] = reset ? (* src = "./src/mux2x1_struct.v:47" *) _05_[3] : 1'h0;
  assign _00_[4] = reset ? (* src = "./src/mux2x1_struct.v:47" *) _05_[4] : 1'h0;
  assign _00_[5] = reset ? (* src = "./src/mux2x1_struct.v:47" *) _05_[5] : 1'h0;
  assign _00_[6] = reset ? (* src = "./src/mux2x1_struct.v:47" *) _05_[6] : 1'h0;
  assign _00_[7] = reset ? (* src = "./src/mux2x1_struct.v:47" *) _05_[7] : 1'h0;
  assign _01_ = reset ? (* src = "./src/mux2x1_struct.v:37" *) _03_ : 1'h0;
  assign _06_ = selector ? (* src = "./src/mux2x1_struct.v:51" *) valid[1] : valid[0];
  assign _02_ = reset ? (* src = "./src/mux2x1_struct.v:47" *) _06_ : 1'h0;
  assign _07_[0] = valid[0] ? (* src = "./src/mux2x1_struct.v:60" *) in0[0] : out[0];
  assign _07_[1] = valid[0] ? (* src = "./src/mux2x1_struct.v:60" *) in0[1] : out[1];
  assign _07_[2] = valid[0] ? (* src = "./src/mux2x1_struct.v:60" *) in0[2] : out[2];
  assign _07_[3] = valid[0] ? (* src = "./src/mux2x1_struct.v:60" *) in0[3] : out[3];
  assign _07_[4] = valid[0] ? (* src = "./src/mux2x1_struct.v:60" *) in0[4] : out[4];
  assign _07_[5] = valid[0] ? (* src = "./src/mux2x1_struct.v:60" *) in0[5] : out[5];
  assign _07_[6] = valid[0] ? (* src = "./src/mux2x1_struct.v:60" *) in0[6] : out[6];
  assign _07_[7] = valid[0] ? (* src = "./src/mux2x1_struct.v:60" *) in0[7] : out[7];
  assign _04_[0] = valid[1] ? (* src = "./src/mux2x1_struct.v:53" *) in1[0] : out[0];
  assign _04_[1] = valid[1] ? (* src = "./src/mux2x1_struct.v:53" *) in1[1] : out[1];
  assign _04_[2] = valid[1] ? (* src = "./src/mux2x1_struct.v:53" *) in1[2] : out[2];
  assign _04_[3] = valid[1] ? (* src = "./src/mux2x1_struct.v:53" *) in1[3] : out[3];
  assign _04_[4] = valid[1] ? (* src = "./src/mux2x1_struct.v:53" *) in1[4] : out[4];
  assign _04_[5] = valid[1] ? (* src = "./src/mux2x1_struct.v:53" *) in1[5] : out[5];
  assign _04_[6] = valid[1] ? (* src = "./src/mux2x1_struct.v:53" *) in1[6] : out[6];
  assign _04_[7] = valid[1] ? (* src = "./src/mux2x1_struct.v:53" *) in1[7] : out[7];
  assign _05_[0] = selector ? (* src = "./src/mux2x1_struct.v:51" *) _04_[0] : _07_[0];
  assign _05_[1] = selector ? (* src = "./src/mux2x1_struct.v:51" *) _04_[1] : _07_[1];
  assign _05_[2] = selector ? (* src = "./src/mux2x1_struct.v:51" *) _04_[2] : _07_[2];
  assign _05_[3] = selector ? (* src = "./src/mux2x1_struct.v:51" *) _04_[3] : _07_[3];
  assign _05_[4] = selector ? (* src = "./src/mux2x1_struct.v:51" *) _04_[4] : _07_[4];
  assign _05_[5] = selector ? (* src = "./src/mux2x1_struct.v:51" *) _04_[5] : _07_[5];
  assign _05_[6] = selector ? (* src = "./src/mux2x1_struct.v:51" *) _04_[6] : _07_[6];
  assign _05_[7] = selector ? (* src = "./src/mux2x1_struct.v:51" *) _04_[7] : _07_[7];
  assign _00_[0] = reset ? (* src = "./src/mux2x1_struct.v:47" *) _05_[0] : 1'h0;
  assign _03_ = ~(* src = "./src/mux2x1_struct.v:40" *) selector;
  (* src = "./src/mux2x1_struct.v:46" *)
  DFF _44_ (
    .C(clk),
    .D(_02_),
    .Q(validout)
  );
  (* src = "./src/mux2x1_struct.v:46" *)
  DFF _45_ (
    .C(clk),
    .D(_00_[0]),
    .Q(out[0])
  );
  (* src = "./src/mux2x1_struct.v:46" *)
  DFF _46_ (
    .C(clk),
    .D(_00_[1]),
    .Q(out[1])
  );
  (* src = "./src/mux2x1_struct.v:46" *)
  DFF _47_ (
    .C(clk),
    .D(_00_[2]),
    .Q(out[2])
  );
  (* src = "./src/mux2x1_struct.v:46" *)
  DFF _48_ (
    .C(clk),
    .D(_00_[3]),
    .Q(out[3])
  );
  (* src = "./src/mux2x1_struct.v:46" *)
  DFF _49_ (
    .C(clk),
    .D(_00_[4]),
    .Q(out[4])
  );
  (* src = "./src/mux2x1_struct.v:46" *)
  DFF _50_ (
    .C(clk),
    .D(_00_[5]),
    .Q(out[5])
  );
  (* src = "./src/mux2x1_struct.v:46" *)
  DFF _51_ (
    .C(clk),
    .D(_00_[6]),
    .Q(out[6])
  );
  (* src = "./src/mux2x1_struct.v:46" *)
  DFF _52_ (
    .C(clk),
    .D(_00_[7]),
    .Q(out[7])
  );
  (* src = "./src/mux2x1_struct.v:36" *)
  DFF _53_ (
    .C(clk),
    .D(_01_),
    .Q(selector)
  );
endmodule
