/* Generated by Yosys 0.9 (git sha1 UNKNOWN, gcc 7.5.0-3ubuntu1~18.04 -fPIC -Os) */
`include "cmos_cells.v" 

(* src = "mux2x1_struct.v:21" *)
module mux2x1_struct(clk, in0, in1, valid, reset, out);
  (* src = "mux2x1_struct.v:43" *)
  wire [7:0] _00_;
  (* src = "mux2x1_struct.v:43" *)
  wire _01_;
  (* src = "mux2x1_struct.v:48" *)
  wire _02_;
  wire [7:0] _03_;
  wire [7:0] _04_;
  wire [7:0] _05_;
  (* src = "mux2x1_struct.v:24" *)
  input clk;
  (* src = "mux2x1_struct.v:25" *)
  input [7:0] in0;
  (* src = "mux2x1_struct.v:26" *)
  input [7:0] in1;
  (* src = "mux2x1_struct.v:31" *)
  output [7:0] out;
  (* src = "mux2x1_struct.v:28" *)
  input reset;
  (* src = "mux2x1_struct.v:35" *)
  wire selector;
  (* src = "mux2x1_struct.v:27" *)
  input [1:0] valid;
  assign _01_ = reset ? (* src = "mux2x1_struct.v:44" *) _02_ : 1'h0;
  assign _05_[0] = valid[0] ? (* src = "mux2x1_struct.v:56" *) in0[0] : out[0];
  assign _05_[1] = valid[0] ? (* src = "mux2x1_struct.v:56" *) in0[1] : out[1];
  assign _05_[2] = valid[0] ? (* src = "mux2x1_struct.v:56" *) in0[2] : out[2];
  assign _05_[3] = valid[0] ? (* src = "mux2x1_struct.v:56" *) in0[3] : out[3];
  assign _05_[4] = valid[0] ? (* src = "mux2x1_struct.v:56" *) in0[4] : out[4];
  assign _05_[5] = valid[0] ? (* src = "mux2x1_struct.v:56" *) in0[5] : out[5];
  assign _05_[6] = valid[0] ? (* src = "mux2x1_struct.v:56" *) in0[6] : out[6];
  assign _05_[7] = valid[0] ? (* src = "mux2x1_struct.v:56" *) in0[7] : out[7];
  assign _03_[0] = valid[1] ? (* src = "mux2x1_struct.v:50" *) in1[0] : out[0];
  assign _03_[1] = valid[1] ? (* src = "mux2x1_struct.v:50" *) in1[1] : out[1];
  assign _03_[2] = valid[1] ? (* src = "mux2x1_struct.v:50" *) in1[2] : out[2];
  assign _03_[3] = valid[1] ? (* src = "mux2x1_struct.v:50" *) in1[3] : out[3];
  assign _03_[4] = valid[1] ? (* src = "mux2x1_struct.v:50" *) in1[4] : out[4];
  assign _03_[5] = valid[1] ? (* src = "mux2x1_struct.v:50" *) in1[5] : out[5];
  assign _03_[6] = valid[1] ? (* src = "mux2x1_struct.v:50" *) in1[6] : out[6];
  assign _03_[7] = valid[1] ? (* src = "mux2x1_struct.v:50" *) in1[7] : out[7];
  assign _04_[0] = selector ? (* src = "mux2x1_struct.v:49" *) _03_[0] : _05_[0];
  assign _04_[1] = selector ? (* src = "mux2x1_struct.v:49" *) _03_[1] : _05_[1];
  assign _04_[2] = selector ? (* src = "mux2x1_struct.v:49" *) _03_[2] : _05_[2];
  assign _04_[3] = selector ? (* src = "mux2x1_struct.v:49" *) _03_[3] : _05_[3];
  assign _04_[4] = selector ? (* src = "mux2x1_struct.v:49" *) _03_[4] : _05_[4];
  assign _04_[5] = selector ? (* src = "mux2x1_struct.v:49" *) _03_[5] : _05_[5];
  assign _04_[6] = selector ? (* src = "mux2x1_struct.v:49" *) _03_[6] : _05_[6];
  assign _04_[7] = selector ? (* src = "mux2x1_struct.v:49" *) _03_[7] : _05_[7];
  assign _00_[0] = reset ? (* src = "mux2x1_struct.v:44" *) _04_[0] : 1'h0;
  assign _00_[1] = reset ? (* src = "mux2x1_struct.v:44" *) _04_[1] : 1'h0;
  assign _00_[2] = reset ? (* src = "mux2x1_struct.v:44" *) _04_[2] : 1'h0;
  assign _00_[3] = reset ? (* src = "mux2x1_struct.v:44" *) _04_[3] : 1'h0;
  assign _00_[4] = reset ? (* src = "mux2x1_struct.v:44" *) _04_[4] : 1'h0;
  assign _00_[5] = reset ? (* src = "mux2x1_struct.v:44" *) _04_[5] : 1'h0;
  assign _00_[6] = reset ? (* src = "mux2x1_struct.v:44" *) _04_[6] : 1'h0;
  assign _00_[7] = reset ? (* src = "mux2x1_struct.v:44" *) _04_[7] : 1'h0;
  assign _02_ = ~(* src = "mux2x1_struct.v:48" *) selector;
  (* src = "mux2x1_struct.v:43" *)
  DFF _40_ (
    .C(clk),
    .D(_00_[0]),
    .Q(out[0])
  );
  (* src = "mux2x1_struct.v:43" *)
  DFF _41_ (
    .C(clk),
    .D(_00_[1]),
    .Q(out[1])
  );
  (* src = "mux2x1_struct.v:43" *)
  DFF _42_ (
    .C(clk),
    .D(_00_[2]),
    .Q(out[2])
  );
  (* src = "mux2x1_struct.v:43" *)
  DFF _43_ (
    .C(clk),
    .D(_00_[3]),
    .Q(out[3])
  );
  (* src = "mux2x1_struct.v:43" *)
  DFF _44_ (
    .C(clk),
    .D(_00_[4]),
    .Q(out[4])
  );
  (* src = "mux2x1_struct.v:43" *)
  DFF _45_ (
    .C(clk),
    .D(_00_[5]),
    .Q(out[5])
  );
  (* src = "mux2x1_struct.v:43" *)
  DFF _46_ (
    .C(clk),
    .D(_00_[6]),
    .Q(out[6])
  );
  (* src = "mux2x1_struct.v:43" *)
  DFF _47_ (
    .C(clk),
    .D(_00_[7]),
    .Q(out[7])
  );
  (* src = "mux2x1_struct.v:43" *)
  DFF _48_ (
    .C(clk),
    .D(_01_),
    .Q(selector)
  );
endmodule

(* top =  1  *)
(* src = "mux4x2_struct.v:23" *)
module mux4x2_struct(clk, in0, in1, in2, in3, valid, reset, out0, out1);
  (* src = "mux4x2_struct.v:26" *)
  input clk;
  (* src = "mux4x2_struct.v:27" *)
  input [7:0] in0;
  (* src = "mux4x2_struct.v:28" *)
  input [7:0] in1;
  (* src = "mux4x2_struct.v:29" *)
  input [7:0] in2;
  (* src = "mux4x2_struct.v:30" *)
  input [7:0] in3;
  (* src = "mux4x2_struct.v:35" *)
  output [7:0] out0;
  (* src = "mux4x2_struct.v:36" *)
  output [7:0] out1;
  (* src = "mux4x2_struct.v:32" *)
  input reset;
  (* src = "mux4x2_struct.v:31" *)
  input [3:0] valid;
  (* src = "mux4x2_struct.v:40" *)
  wire [7:0] wout0;
  (* src = "mux4x2_struct.v:41" *)
  wire [7:0] wout1;
  (* module_not_derived = 32'd1 *)
  (* src = "mux4x2_struct.v:44" *)
  mux2x1_struct mux_A (
    .clk(clk),
    .in0(in0),
    .in1(in1),
    .out(wout0),
    .reset(reset),
    .valid(valid[1:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "mux4x2_struct.v:52" *)
  mux2x1_struct mux_B (
    .clk(clk),
    .in0(in2),
    .in1(in3),
    .out(wout1),
    .reset(reset),
    .valid(valid[3:2])
  );
  assign out0 = wout0;
  assign out1 = wout1;
endmodule
