/* Generated by Yosys 0.9 (git sha1 UNKNOWN, gcc 7.5.0-3ubuntu1~18.04 -fPIC -Os) */

(* top =  1  *)
(* src = "paralelltoserial.v:4" *)
module paralelo_a_serial(in, in_valid, reset, clk32f, out);
  (* src = "paralelltoserial.v:24" *)
  wire _00_;
  (* src = "paralelltoserial.v:24" *)
  wire [2:0] _01_;
  (* src = "paralelltoserial.v:34" *)
  (* unused_bits = "3" *)
  wire [31:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [2:0] _07_;
  wire [1:0] _08_;
  wire [2:0] _09_;
  wire [1:0] _10_;
  wire _11_;
  wire [2:0] _12_;
  wire [2:0] _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:432" *)
  wire [6:0] _20_;
  (* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:428" *)
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  (* src = "paralelltoserial.v:34|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2" *)
  wire [31:0] _30_;
  (* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:445" *)
  wire _31_;
  (* src = "paralelltoserial.v:9" *)
  input clk32f;
  (* src = "paralelltoserial.v:6" *)
  input [7:0] in;
  (* src = "paralelltoserial.v:13" *)
  wire in0;
  (* src = "paralelltoserial.v:13" *)
  wire in1;
  (* src = "paralelltoserial.v:13" *)
  wire in2;
  (* src = "paralelltoserial.v:13" *)
  wire in3;
  (* src = "paralelltoserial.v:13" *)
  wire in4;
  (* src = "paralelltoserial.v:13" *)
  wire in5;
  (* src = "paralelltoserial.v:13" *)
  wire in6;
  (* src = "paralelltoserial.v:13" *)
  wire in7;
  (* src = "paralelltoserial.v:7" *)
  input in_valid;
  (* src = "paralelltoserial.v:10" *)
  output out;
  (* src = "paralelltoserial.v:8" *)
  input reset;
  (* src = "paralelltoserial.v:14" *)
  wire [2:0] selector;
  assign _14_ = _03_ |(* src = "paralelltoserial.v:42|paralelltoserial.v:35" *)  _12_[2];
  assign _15_ = _04_ |(* src = "paralelltoserial.v:41|paralelltoserial.v:35" *)  _12_[2];
  assign _16_ = _05_ |(* src = "paralelltoserial.v:40|paralelltoserial.v:35" *)  _12_[2];
  assign _06_ = _02_[0] |(* src = "paralelltoserial.v:39|paralelltoserial.v:35" *)  _13_[1];
  assign _17_ = _06_ |(* src = "paralelltoserial.v:39|paralelltoserial.v:35" *)  selector[2];
  assign _03_ = selector[0] |(* src = "paralelltoserial.v:38|paralelltoserial.v:35" *)  _13_[1];
  assign _18_ = _03_ |(* src = "paralelltoserial.v:38|paralelltoserial.v:35" *)  selector[2];
  assign _04_ = _02_[0] |(* src = "paralelltoserial.v:37|paralelltoserial.v:35" *)  selector[1];
  assign _19_ = _04_ |(* src = "paralelltoserial.v:37|paralelltoserial.v:35" *)  selector[2];
  assign _07_[0] = _20_[0] |(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:441" *)  _20_[1];
  assign _07_[1] = _20_[2] |(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:441" *)  _20_[3];
  assign _07_[2] = _20_[4] |(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:441" *)  _20_[5];
  assign _08_[0] = _07_[0] |(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:441" *)  _07_[1];
  assign _08_[1] = _07_[2] |(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:441" *)  _20_[6];
  assign _21_ = _08_[0] |(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:441" *)  _08_[1];
  assign _09_[0] = _23_ |(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:445" *)  _24_;
  assign _09_[1] = _25_ |(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:445" *)  _26_;
  assign _09_[2] = _27_ |(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:445" *)  _28_;
  assign _10_[0] = _09_[0] |(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:445" *)  _09_[1];
  assign _10_[1] = _09_[2] |(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:445" *)  _29_;
  assign _31_ = _10_[0] |(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:445" *)  _10_[1];
  assign _05_ = selector[0] |(* src = "paralelltoserial.v:36|paralelltoserial.v:35" *)  selector[1];
  assign _11_ = _05_ |(* src = "paralelltoserial.v:36|paralelltoserial.v:35" *)  selector[2];
  assign _23_ = ~(* src = "paralelltoserial.v:42|paralelltoserial.v:35" *) _14_;
  assign _24_ = ~(* src = "paralelltoserial.v:41|paralelltoserial.v:35" *) _15_;
  assign _25_ = ~(* src = "paralelltoserial.v:40|paralelltoserial.v:35" *) _16_;
  assign _26_ = ~(* src = "paralelltoserial.v:39|paralelltoserial.v:35" *) _17_;
  assign _27_ = ~(* src = "paralelltoserial.v:38|paralelltoserial.v:35" *) _18_;
  assign _28_ = ~(* src = "paralelltoserial.v:37|paralelltoserial.v:35" *) _19_;
  assign _29_ = ~(* src = "paralelltoserial.v:36|paralelltoserial.v:35" *) _11_;
  assign _00_ = reset ? (* src = "paralelltoserial.v:25" *) _22_ : 1'h0;
  assign in7 = in_valid ? (* src = "paralelltoserial.v:18" *) in[0] : 1'h0;
  assign in0 = in_valid ? (* src = "paralelltoserial.v:18" *) in[7] : 1'h1;
  assign in1 = in_valid ? (* src = "paralelltoserial.v:18" *) in[6] : 1'h0;
  assign in5 = in_valid ? (* src = "paralelltoserial.v:18" *) in[2] : 1'h1;
  assign in6 = in_valid ? (* src = "paralelltoserial.v:18" *) in[1] : 1'h0;
  assign in2 = in_valid ? (* src = "paralelltoserial.v:18" *) in[5] : 1'h1;
  assign in4 = in_valid ? (* src = "paralelltoserial.v:18" *) in[3] : 1'h1;
  assign in3 = in_valid ? (* src = "paralelltoserial.v:18" *) in[4] : 1'h1;
  assign _22_ = _31_ ? (* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:445" *) _21_ : in7;
  assign _01_[0] = reset ? (* src = "paralelltoserial.v:25" *) _02_[0] : 1'h0;
  assign _01_[1] = reset ? (* src = "paralelltoserial.v:25" *) _02_[1] : 1'h0;
  assign _01_[2] = reset ? (* src = "paralelltoserial.v:25" *) _02_[2] : 1'h0;
  (* src = "paralelltoserial.v:24" *)
  DFF _75_ (
    .C(clk32f),
    .D(_00_),
    .Q(out)
  );
  (* src = "paralelltoserial.v:24" *)
  DFF _76_ (
    .C(clk32f),
    .D(_01_[0]),
    .Q(selector[0])
  );
  (* src = "paralelltoserial.v:24" *)
  DFF _77_ (
    .C(clk32f),
    .D(_01_[1]),
    .Q(selector[1])
  );
  (* src = "paralelltoserial.v:24" *)
  DFF _78_ (
    .C(clk32f),
    .D(_01_[2]),
    .Q(selector[2])
  );
  assign _12_[2] = selector[2] ^(* src = "paralelltoserial.v:40|paralelltoserial.v:35" *)  1'h1;
  assign _13_[1] = selector[1] ^(* src = "paralelltoserial.v:38|paralelltoserial.v:35" *)  1'h1;
  assign _20_[3] = in3 &(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:434" *)  _26_;
  assign _20_[6] = in0 &(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:434" *)  _29_;
  assign _20_[5] = in1 &(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:434" *)  _28_;
  assign _20_[4] = in2 &(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:434" *)  _27_;
  assign _20_[2] = in4 &(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:434" *)  _25_;
  assign _20_[1] = in5 &(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:434" *)  _24_;
  assign _20_[0] = in6 &(* src = "paralelltoserial.v:42|paralelltoserial.v:35|<techmap.v>:434" *)  _23_;
  assign _02_[1] = selector[1] ^(* src = "paralelltoserial.v:34|<techmap.v>:263" *)  selector[0];
  assign _02_[2] = selector[2] ^(* src = "paralelltoserial.v:34|<techmap.v>:263" *)  _30_[1];
  assign _02_[0] = selector[0] ^(* src = "paralelltoserial.v:34|<techmap.v>:262" *)  1'h1;
  assign _30_[1] = selector[1] &(* src = "paralelltoserial.v:34|<techmap.v>:260|<techmap.v>:221" *)  selector[0];
  assign _02_[31:4] = 28'h0000000;
  assign _12_[1:0] = { selector[1], _02_[0] };
  assign { _13_[2], _13_[0] } = { selector[2], _02_[0] };
  assign { _30_[31:2], _30_[0] } = { 29'h00000000, _02_[3], selector[0] };
endmodule
